# Generated by Django 4.2 on 2023-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_order_products_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='market.OrderItem', to='market.product'),
        ),
    ]
