# Generated by Django 4.2 on 2023-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_promotion', models.BooleanField(default=False)),
                ('is_reduction', models.BooleanField(default=False)),
                ('value', models.IntegerField(blank=True, default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
