# Generated by Django 4.2 on 2023-06-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_promotioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioncode',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotioncode',
            name='min_value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
