# Generated by Django 4.2 on 2023-06-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_order_date_order_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
